import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Louise Kerin Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <div className="container">{children}</div>
        <footer>
          <p>Louise Kerin &copy; 2023</p>
        </footer>
      </body>
    </html>
  );
}
