import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { url } from "inspector";

export const metadata = {
  title: "Louise Kerin Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/cam2uni.css" />
      </head>
      <body>
        <Header></Header>
        <div className>{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
